##################################
###########IN PROGRESS############
##################################


# Install and Load Packages
install.packages("doBy")
library(doBy)

# Import CSV
data <- read.csv("~/Desktop/MW_H_2008.csv")

# Define Functions
weightsum <- function(x) return(sum(x)*10)
narm_mean <- function(x) return(mean(x, na.rm=TRUE))

# Collapse to Household Level for HH Variables
hhdata <- summaryBy(. ~ SERIAL + GEO2A_MW, FUN=mean, data=data)


# Create Collapsed Variable: PERSONS
persons <- summaryBy(PERSONS.mean ~ GEO2A_MW, FUN=weightsum, data=hhdata)


# Separate Variable: URBAN
hhdata$urban_0 <- ifelse(hhdata$URBAN.mean==0,1,0)
hhdata$urban_1 <- ifelse(hhdata$URBAN.mean==1,1,0)
hhdata$urban_2 <- ifelse(hhdata$URBAN.mean==2,1,0)
hhdata$urban_9 <- ifelse(hhdata$URBAN.mean==9,1,0)
# Create Collapsed Variabes: URBAN
urban_0 <- summaryBy(urban_0 ~ GEO2A_MW, FUN=mean, data=hhdata)
urban_1 <- summaryBy(urban_1 ~ GEO2A_MW, FUN=mean, data=hhdata)
urban_2 <- summaryBy(urban_2 ~ GEO2A_MW, FUN=mean, data=hhdata)
urban_9 <- summaryBy(urban_9 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: URBAN
urban <- merge(urban_0, urban_1, by="GEO2A_MW")
urban <- merge(urban, urban_2, by="GEO2A_MW")
urban <- merge(urban, urban_9, by="GEO2A_MW")


# Create Collapsed Variable: UNREL
unrel <- summaryBy(UNREL.mean ~ GEO2A_MW, FUN=weightsum, data=hhdata)


# Separate Variable: OWNRSHP
hhdata$ownrshp_0 <- ifelse(hhdata$OWNRSHP.mean==0,1,0)
hhdata$ownrshp_1 <- ifelse(hhdata$OWNRSHP.mean==1,1,0)
hhdata$ownrshp_2 <- ifelse(hhdata$OWNRSHP.mean==2,1,0)
hhdata$ownrshp_9 <- ifelse(hhdata$OWNRSHP.mean==9,1,0)
# Create Collapsed Variabes: OWNRSHP
ownrshp_0 <- summaryBy(ownrshp_0 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshp_1 <- summaryBy(ownrshp_1 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshp_2 <- summaryBy(ownrshp_2 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshp_9 <- summaryBy(ownrshp_9 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: OWNRSHP
ownrshp <- merge(ownrshp_0, ownrshp_1, by="GEO2A_MW")
ownrshp <- merge(ownrshp, ownrshp_2, by="GEO2A_MW")
ownrshp <- merge(ownrshp, ownrshp_9, by="GEO2A_MW")

# Separate Variable: OWNRSHPD
hhdata$ownrshpd_000 <- ifelse(hhdata$OWNRSHPD.mean==000,1,0)
hhdata$ownrshpd_100 <- ifelse(hhdata$OWNRSHPD.mean==100,1,0)
hhdata$ownrshpd_110 <- ifelse(hhdata$OWNRSHPD.mean==110,1,0)
hhdata$ownrshpd_120 <- ifelse(hhdata$OWNRSHPD.mean==120,1,0)
hhdata$ownrshpd_130 <- ifelse(hhdata$OWNRSHPD.mean==130,1,0)
hhdata$ownrshpd_140 <- ifelse(hhdata$OWNRSHPD.mean==140,1,0)
hhdata$ownrshpd_190 <- ifelse(hhdata$OWNRSHPD.mean==190,1,0)
hhdata$ownrshpd_191 <- ifelse(hhdata$OWNRSHPD.mean==191,1,0)
hhdata$ownrshpd_192 <- ifelse(hhdata$OWNRSHPD.mean==192,1,0)
hhdata$ownrshpd_193 <- ifelse(hhdata$OWNRSHPD.mean==193,1,0)
hhdata$ownrshpd_194 <- ifelse(hhdata$OWNRSHPD.mean==194,1,0)
hhdata$ownrshpd_200 <- ifelse(hhdata$OWNRSHPD.mean==200,1,0)
hhdata$ownrshpd_210 <- ifelse(hhdata$OWNRSHPD.mean==210,1,0)
hhdata$ownrshpd_211 <- ifelse(hhdata$OWNRSHPD.mean==211,1,0)
hhdata$ownrshpd_212 <- ifelse(hhdata$OWNRSHPD.mean==212,1,0)
hhdata$ownrshpd_213 <- ifelse(hhdata$OWNRSHPD.mean==213,1,0)
hhdata$ownrshpd_214 <- ifelse(hhdata$OWNRSHPD.mean==214,1,0)
hhdata$ownrshpd_215 <- ifelse(hhdata$OWNRSHPD.mean==215,1,0)
hhdata$ownrshpd_216 <- ifelse(hhdata$OWNRSHPD.mean==216,1,0)
hhdata$ownrshpd_217 <- ifelse(hhdata$OWNRSHPD.mean==217,1,0)
hhdata$ownrshpd_218 <- ifelse(hhdata$OWNRSHPD.mean==218,1,0)
hhdata$ownrshpd_219 <- ifelse(hhdata$OWNRSHPD.mean==219,1,0)
hhdata$ownrshpd_220 <- ifelse(hhdata$OWNRSHPD.mean==220,1,0)
hhdata$ownrshpd_221 <- ifelse(hhdata$OWNRSHPD.mean==221,1,0)
hhdata$ownrshpd_222 <- ifelse(hhdata$OWNRSHPD.mean==222,1,0)
hhdata$ownrshpd_223 <- ifelse(hhdata$OWNRSHPD.mean==223,1,0)
hhdata$ownrshpd_224 <- ifelse(hhdata$OWNRSHPD.mean==224,1,0)
hhdata$ownrshpd_225 <- ifelse(hhdata$OWNRSHPD.mean==225,1,0)
hhdata$ownrshpd_226 <- ifelse(hhdata$OWNRSHPD.mean==226,1,0)
hhdata$ownrshpd_227 <- ifelse(hhdata$OWNRSHPD.mean==227,1,0)
hhdata$ownrshpd_228 <- ifelse(hhdata$OWNRSHPD.mean==228,1,0)
hhdata$ownrshpd_230 <- ifelse(hhdata$OWNRSHPD.mean==230,1,0)
hhdata$ownrshpd_231 <- ifelse(hhdata$OWNRSHPD.mean==231,1,0)
hhdata$ownrshpd_239 <- ifelse(hhdata$OWNRSHPD.mean==239,1,0)
hhdata$ownrshpd_240 <- ifelse(hhdata$OWNRSHPD.mean==240,1,0)
hhdata$ownrshpd_250 <- ifelse(hhdata$OWNRSHPD.mean==250,1,0)
hhdata$ownrshpd_251 <- ifelse(hhdata$OWNRSHPD.mean==251,1,0)
hhdata$ownrshpd_252 <- ifelse(hhdata$OWNRSHPD.mean==252,1,0)
hhdata$ownrshpd_253 <- ifelse(hhdata$OWNRSHPD.mean==253,1,0)
hhdata$ownrshpd_254 <- ifelse(hhdata$OWNRSHPD.mean==254,1,0)
hhdata$ownrshpd_255 <- ifelse(hhdata$OWNRSHPD.mean==255,1,0)
hhdata$ownrshpd_256 <- ifelse(hhdata$OWNRSHPD.mean==256,1,0)
hhdata$ownrshpd_257 <- ifelse(hhdata$OWNRSHPD.mean==257,1,0)
hhdata$ownrshpd_290 <- ifelse(hhdata$OWNRSHPD.mean==290,1,0)
hhdata$ownrshpd_999 <- ifelse(hhdata$OWNRSHPD.mean==999,1,0)
# Create Collapsed Variabes: OWNRSHPD
ownrshpd_000 <- summaryBy(ownrshpd_000 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_100 <- summaryBy(ownrshpd_100 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_110 <- summaryBy(ownrshpd_110 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_120 <- summaryBy(ownrshpd_120 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_130 <- summaryBy(ownrshpd_130 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_140 <- summaryBy(ownrshpd_140 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_190 <- summaryBy(ownrshpd_190 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_191 <- summaryBy(ownrshpd_191 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_192 <- summaryBy(ownrshpd_192 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_193 <- summaryBy(ownrshpd_193 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_194 <- summaryBy(ownrshpd_194 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_200 <- summaryBy(ownrshpd_200 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_210 <- summaryBy(ownrshpd_210 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_211 <- summaryBy(ownrshpd_211 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_212 <- summaryBy(ownrshpd_212 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_213 <- summaryBy(ownrshpd_213 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_214 <- summaryBy(ownrshpd_214 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_215 <- summaryBy(ownrshpd_215 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_216 <- summaryBy(ownrshpd_216 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_217 <- summaryBy(ownrshpd_217 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_218 <- summaryBy(ownrshpd_218 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_219 <- summaryBy(ownrshpd_219 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_220 <- summaryBy(ownrshpd_220 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_221 <- summaryBy(ownrshpd_221 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_222 <- summaryBy(ownrshpd_222 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_223 <- summaryBy(ownrshpd_223 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_224 <- summaryBy(ownrshpd_224 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_225 <- summaryBy(ownrshpd_225 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_226 <- summaryBy(ownrshpd_226 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_227 <- summaryBy(ownrshpd_227 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_228 <- summaryBy(ownrshpd_228 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_230 <- summaryBy(ownrshpd_230 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_231 <- summaryBy(ownrshpd_231 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_239 <- summaryBy(ownrshpd_239 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_240 <- summaryBy(ownrshpd_240 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_250 <- summaryBy(ownrshpd_250 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_251 <- summaryBy(ownrshpd_251 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_252 <- summaryBy(ownrshpd_252 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_253 <- summaryBy(ownrshpd_253 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_254 <- summaryBy(ownrshpd_254 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_255 <- summaryBy(ownrshpd_255 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_256 <- summaryBy(ownrshpd_256 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_257 <- summaryBy(ownrshpd_257 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_290 <- summaryBy(ownrshpd_290 ~ GEO2A_MW, FUN=mean, data=hhdata)
ownrshpd_999 <- summaryBy(ownrshpd_999 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: OWNRSHPD
ownrshpd <- merge(ownrshpd_000, ownrshpd_100, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_110, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_120, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_130, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_140, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_190, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_191, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_192, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_193, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_194, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_200, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_210, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_211, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_212, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_213, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_214, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_215, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_216, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_217, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_218, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_219, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_220, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_221, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_222, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_223, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_224, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_225, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_226, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_227, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_228, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_230, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_231, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_239, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_240, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_250, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_251, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_252, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_253, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_254, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_255, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_256, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_257, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_290, by="GEO2A_MW")
ownrshpd <- merge(ownrshpd, ownrshpd_999, by="GEO2A_MW")


# Remove unknown values: INTMIG1
hhdata$INTMIG1.mean[hhdata$INTMIG1.mean==98] <- NA
hhdata$INTMIG1.mean[hhdata$INTMIG1.mean==99] <- NA
# Create Collapsed Variable: INTMIG1
intmig1 <- summaryBy(INTMIG1.mean ~ GEO2A_MW, FUN=weightsum, data=hhdata)


# Separate Variable: REMITT
hhdata$remitt_0 <- ifelse(hhdata$REMITT.mean==0,1,0)
hhdata$remitt_1 <- ifelse(hhdata$REMITT.mean==1,1,0)
hhdata$remitt_2 <- ifelse(hhdata$REMITT.mean==2,1,0)
hhdata$remitt_9 <- ifelse(hhdata$REMITT.mean==9,1,0)
# Create Collapsed Variabes: REMITT
remitt_0 <- summaryBy(remitt_0 ~ GEO2A_MW, FUN=mean, data=hhdata)
remitt_1 <- summaryBy(remitt_1 ~ GEO2A_MW, FUN=mean, data=hhdata)
remitt_2 <- summaryBy(remitt_2 ~ GEO2A_MW, FUN=mean, data=hhdata)
remitt_9 <- summaryBy(remitt_9 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: REMITT
remitt <- merge(remitt_0, remitt_1, by="GEO2A_MW")
remitt <- merge(remitt, remitt_2, by="GEO2A_MW")
remitt <- merge(remitt, remitt_9, by="GEO2A_MW")


# Separate Variable: ELECTRC
hhdata$electrc_0 <- ifelse(hhdata$ELECTRC.mean==0,1,0)
hhdata$electrc_1 <- ifelse(hhdata$ELECTRC.mean==1,1,0)
hhdata$electrc_2 <- ifelse(hhdata$ELECTRC.mean==2,1,0)
hhdata$electrc_9 <- ifelse(hhdata$ELECTRC.mean==9,1,0)
# Create Collapsed Variabes: ELECTRC
electrc_0 <- summaryBy(electrc_0 ~ GEO2A_MW, FUN=mean, data=hhdata)
electrc_1 <- summaryBy(electrc_1 ~ GEO2A_MW, FUN=mean, data=hhdata)
electrc_2 <- summaryBy(electrc_2 ~ GEO2A_MW, FUN=mean, data=hhdata)
electrc_9 <- summaryBy(electrc_9 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: ELECTRC
electrc <- merge(electrc_0, electrc_1, by="GEO2A_MW")
electrc <- merge(electrc, electrc_2, by="GEO2A_MW")
electrc <- merge(electrc, electrc_9, by="GEO2A_MW")

# Separate Variable: WATSUP
hhdata$watsup_00 <- ifelse(hhdata$WATSUP.mean==00,1,0)
hhdata$watsup_10 <- ifelse(hhdata$WATSUP.mean==10,1,0)
hhdata$watsup_11 <- ifelse(hhdata$WATSUP.mean==11,1,0)
hhdata$watsup_12 <- ifelse(hhdata$WATSUP.mean==12,1,0)
hhdata$watsup_13 <- ifelse(hhdata$WATSUP.mean==13,1,0)
hhdata$watsup_14 <- ifelse(hhdata$WATSUP.mean==14,1,0)
hhdata$watsup_15 <- ifelse(hhdata$WATSUP.mean==15,1,0)
hhdata$watsup_16 <- ifelse(hhdata$WATSUP.mean==16,1,0)
hhdata$watsup_17 <- ifelse(hhdata$WATSUP.mean==17,1,0)
hhdata$watsup_18 <- ifelse(hhdata$WATSUP.mean==18,1,0)
hhdata$watsup_20 <- ifelse(hhdata$WATSUP.mean==20,1,0)
hhdata$watsup_99 <- ifelse(hhdata$WATSUP.mean==99,1,0)
# Create Collapsed Variabes: WATSUP
watsup_00 <- summaryBy(watsup_00 ~ GEO2A_MW, FUN=mean, data=hhdata)
watsup_10 <- summaryBy(watsup_10 ~ GEO2A_MW, FUN=mean, data=hhdata)
watsup_11 <- summaryBy(watsup_11 ~ GEO2A_MW, FUN=mean, data=hhdata)
watsup_12 <- summaryBy(watsup_12 ~ GEO2A_MW, FUN=mean, data=hhdata)
watsup_13 <- summaryBy(watsup_13 ~ GEO2A_MW, FUN=mean, data=hhdata)
watsup_14 <- summaryBy(watsup_14 ~ GEO2A_MW, FUN=mean, data=hhdata)
watsup_15 <- summaryBy(watsup_15 ~ GEO2A_MW, FUN=mean, data=hhdata)
watsup_16 <- summaryBy(watsup_16 ~ GEO2A_MW, FUN=mean, data=hhdata)
watsup_17 <- summaryBy(watsup_17 ~ GEO2A_MW, FUN=mean, data=hhdata)
watsup_18 <- summaryBy(watsup_18 ~ GEO2A_MW, FUN=mean, data=hhdata)
watsup_20 <- summaryBy(watsup_20 ~ GEO2A_MW, FUN=mean, data=hhdata)
watsup_99 <- summaryBy(watsup_99 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: WATSUP
watsup <- merge(watsup_00, watsup_10, by="GEO2A_MW")
watsup <- merge(watsup, watsup_11, by="GEO2A_MW")
watsup <- merge(watsup, watsup_12, by="GEO2A_MW")
watsup <- merge(watsup, watsup_13, by="GEO2A_MW")
watsup <- merge(watsup, watsup_14, by="GEO2A_MW")
watsup <- merge(watsup, watsup_15, by="GEO2A_MW")
watsup <- merge(watsup, watsup_16, by="GEO2A_MW")
watsup <- merge(watsup, watsup_17, by="GEO2A_MW")
watsup <- merge(watsup, watsup_18, by="GEO2A_MW")
watsup <- merge(watsup, watsup_20, by="GEO2A_MW")
watsup <- merge(watsup, watsup_99, by="GEO2A_MW")


# Separate Variable: FUELCK
hhdata$fuelck_00 <- ifelse(hhdata$FUELCK.mean==00,1,0)
hhdata$fuelck_10 <- ifelse(hhdata$FUELCK.mean==10,1,0)
hhdata$fuelck_20 <- ifelse(hhdata$FUELCK.mean==20,1,0)
hhdata$fuelck_30 <- ifelse(hhdata$FUELCK.mean==30,1,0)
hhdata$fuelck_31 <- ifelse(hhdata$FUELCK.mean==31,1,0)
hhdata$fuelck_32 <- ifelse(hhdata$FUELCK.mean==32,1,0)
hhdata$fuelck_33 <- ifelse(hhdata$FUELCK.mean==33,1,0)
hhdata$fuelck_35 <- ifelse(hhdata$FUELCK.mean==35,1,0)
hhdata$fuelck_40 <- ifelse(hhdata$FUELCK.mean==40,1,0)
hhdata$fuelck_41 <- ifelse(hhdata$FUELCK.mean==41,1,0)
hhdata$fuelck_42 <- ifelse(hhdata$FUELCK.mean==42,1,0)
hhdata$fuelck_43 <- ifelse(hhdata$FUELCK.mean==43,1,0)
hhdata$fuelck_44 <- ifelse(hhdata$FUELCK.mean==44,1,0)
hhdata$fuelck_45 <- ifelse(hhdata$FUELCK.mean==45,1,0)
hhdata$fuelck_46 <- ifelse(hhdata$FUELCK.mean==46,1,0)
hhdata$fuelck_50 <- ifelse(hhdata$FUELCK.mean==50,1,0)
hhdata$fuelck_51 <- ifelse(hhdata$FUELCK.mean==51,1,0)
hhdata$fuelck_52 <- ifelse(hhdata$FUELCK.mean==52,1,0)
hhdata$fuelck_53 <- ifelse(hhdata$FUELCK.mean==53,1,0)
hhdata$fuelck_54 <- ifelse(hhdata$FUELCK.mean==54,1,0)
hhdata$fuelck_55 <- ifelse(hhdata$FUELCK.mean==55,1,0)
hhdata$fuelck_56 <- ifelse(hhdata$FUELCK.mean==56,1,0)
hhdata$fuelck_60 <- ifelse(hhdata$FUELCK.mean==60,1,0)
hhdata$fuelck_61 <- ifelse(hhdata$FUELCK.mean==61,1,0)
hhdata$fuelck_62 <- ifelse(hhdata$FUELCK.mean==62,1,0)
hhdata$fuelck_63 <- ifelse(hhdata$FUELCK.mean==63,1,0)
hhdata$fuelck_64 <- ifelse(hhdata$FUELCK.mean==64,1,0)
hhdata$fuelck_65 <- ifelse(hhdata$FUELCK.mean==65,1,0)
hhdata$fuelck_66 <- ifelse(hhdata$FUELCK.mean==66,1,0)
hhdata$fuelck_70 <- ifelse(hhdata$FUELCK.mean==70,1,0)
hhdata$fuelck_71 <- ifelse(hhdata$FUELCK.mean==71,1,0)
hhdata$fuelck_72 <- ifelse(hhdata$FUELCK.mean==72,1,0)
hhdata$fuelck_73 <- ifelse(hhdata$FUELCK.mean==73,1,0)
hhdata$fuelck_74 <- ifelse(hhdata$FUELCK.mean==74,1,0)
hhdata$fuelck_75 <- ifelse(hhdata$FUELCK.mean==75,1,0)
hhdata$fuelck_76 <- ifelse(hhdata$FUELCK.mean==76,1,0)
hhdata$fuelck_77 <- ifelse(hhdata$FUELCK.mean==77,1,0)
hhdata$fuelck_99 <- ifelse(hhdata$FUELCK.mean==99,1,0)
# Create Collapsed Variabes: FUELCK
fuelck_00 <- summaryBy(fuelck_00 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_10 <- summaryBy(fuelck_10 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_20 <- summaryBy(fuelck_20 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_30 <- summaryBy(fuelck_30 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_31 <- summaryBy(fuelck_31 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_32 <- summaryBy(fuelck_32 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_33 <- summaryBy(fuelck_33 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_35 <- summaryBy(fuelck_35 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_40 <- summaryBy(fuelck_40 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_41 <- summaryBy(fuelck_41 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_42 <- summaryBy(fuelck_42 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_43 <- summaryBy(fuelck_43 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_44 <- summaryBy(fuelck_44 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_45 <- summaryBy(fuelck_45 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_46 <- summaryBy(fuelck_46 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_50 <- summaryBy(fuelck_50 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_51 <- summaryBy(fuelck_51 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_52 <- summaryBy(fuelck_52 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_53 <- summaryBy(fuelck_53 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_54 <- summaryBy(fuelck_54 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_55 <- summaryBy(fuelck_55 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_56 <- summaryBy(fuelck_56 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_60 <- summaryBy(fuelck_60 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_61 <- summaryBy(fuelck_61 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_62 <- summaryBy(fuelck_62 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_63 <- summaryBy(fuelck_63 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_64 <- summaryBy(fuelck_64 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_65 <- summaryBy(fuelck_65 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_66 <- summaryBy(fuelck_66 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_70 <- summaryBy(fuelck_70 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_71 <- summaryBy(fuelck_71 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_72 <- summaryBy(fuelck_72 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_73 <- summaryBy(fuelck_73 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_74 <- summaryBy(fuelck_74 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_75 <- summaryBy(fuelck_75 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_76 <- summaryBy(fuelck_76 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_77 <- summaryBy(fuelck_77 ~ GEO2A_MW, FUN=mean, data=hhdata)
fuelck_99 <- summaryBy(fuelck_99 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: FUELCK
fuelck <- merge(fuelck_00, fuelck_10, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_20, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_30, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_31, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_32, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_33, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_34, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_35, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_40, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_41, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_42, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_43, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_44, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_45, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_46, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_50, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_51, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_52, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_53, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_54, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_55, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_56, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_60, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_61, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_62, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_63, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_64, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_65, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_66, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_70, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_71, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_72, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_73, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_74, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_75, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_76, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_77, by="GEO2A_MW")
fuelck <- merge(fuelck, fuelck_99, by="GEO2A_MW")


# Separate Variable: PHONE
hhdata$phone_0 <- ifelse(hhdata$PHONE.mean==0,1,0)
hhdata$phone_1 <- ifelse(hhdata$PHONE.mean==1,1,0)
hhdata$phone_2 <- ifelse(hhdata$PHONE.mean==2,1,0)
hhdata$phone_9 <- ifelse(hhdata$PHONE.mean==9,1,0)
# Create Collapsed Variabes: PHONE
phone_0 <- summaryBy(phone_0 ~ GEO2A_MW, FUN=mean, data=hhdata)
phone_1 <- summaryBy(phone_1 ~ GEO2A_MW, FUN=mean, data=hhdata)
phone_2 <- summaryBy(phone_2 ~ GEO2A_MW, FUN=mean, data=hhdata)
phone_9 <- summaryBy(phone_9 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: PHONE
phone <- merge(phone_0, phone_1, by="GEO2A_MW")
phone <- merge(phone, phone_2, by="GEO2A_MW")
phone <- merge(phone, phone_9, by="GEO2A_MW")


# Change 'Have auto, number unspecified' to '1'
hhdata$AUTOS.mean[hhdata$AUTOS.mean==7] <- 1
# Remove unknown values: AUTOS
hhdata$AUTOS.mean[hhdata$AUTOS.mean==8] <- NA
hhdata$AUTOS.mean[hhdata$AUTOS.mean==9] <- NA
#Create Collapsed Variable: AUTOS
autos <- summaryBy(AUTOS.mean ~ GEO2A_MW, FUN=narm_mean, data=hhdata)


# Separate Variable: REFRIG
hhdata$refrig_0 <- ifelse(hhdata$REFRIG.mean==0,1,0)
hhdata$refrig_1 <- ifelse(hhdata$REFRIG.mean==1,1,0)
hhdata$refrig_2 <- ifelse(hhdata$REFRIG.mean==2,1,0)
hhdata$refrig_9 <- ifelse(hhdata$REFRIG.mean==9,1,0)
# Create Collapsed Variabes: REFRIG
refrig_0 <- summaryBy(refrig_0 ~ GEO2A_MW, FUN=mean, data=hhdata)
refrig_1 <- summaryBy(refrig_1 ~ GEO2A_MW, FUN=mean, data=hhdata)
refrig_2 <- summaryBy(refrig_2 ~ GEO2A_MW, FUN=mean, data=hhdata)
refrig_9 <- summaryBy(refrig_9 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: REFRIG
refrig <- merge(refrig_0, refrig_1, by="GEO2A_MW")
refrig <- merge(refrig, refrig_2, by="GEO2A_MW")
refrig <- merge(refrig, refrig_9, by="GEO2A_MW")


# Separate Variable: TV
hhdata$tv_00 <- ifelse(hhdata$TV.mean==00,1,0)
hhdata$tv_10 <- ifelse(hhdata$TV.mean==10,1,0)
hhdata$tv_20 <- ifelse(hhdata$TV.mean==20,1,0)
hhdata$tv_21 <- ifelse(hhdata$TV.mean==21,1,0)
hhdata$tv_22 <- ifelse(hhdata$TV.mean==22,1,0)
hhdata$tv_23 <- ifelse(hhdata$TV.mean==23,1,0)
hhdata$tv_24 <- ifelse(hhdata$TV.mean==24,1,0)
hhdata$tv_25 <- ifelse(hhdata$TV.mean==25,1,0)
hhdata$tv_26 <- ifelse(hhdata$TV.mean==26,1,0)
hhdata$tv_27 <- ifelse(hhdata$TV.mean==27,1,0)
hhdata$tv_28 <- ifelse(hhdata$TV.mean==28,1,0)
hhdata$tv_29 <- ifelse(hhdata$TV.mean==29,1,0)
hhdata$tv_30 <- ifelse(hhdata$TV.mean==30,1,0)
hhdata$tv_31 <- ifelse(hhdata$TV.mean==31,1,0)
hhdata$tv_32 <- ifelse(hhdata$TV.mean==32,1,0)
hhdata$tv_33 <- ifelse(hhdata$TV.mean==33,1,0)
hhdata$tv_40 <- ifelse(hhdata$TV.mean==40,1,0)
hhdata$tv_41 <- ifelse(hhdata$TV.mean==41,1,0)
hhdata$tv_42 <- ifelse(hhdata$TV.mean==42,1,0)
hhdata$tv_43 <- ifelse(hhdata$TV.mean==43,1,0)
hhdata$tv_50 <- ifelse(hhdata$TV.mean==50,1,0)
hhdata$tv_52 <- ifelse(hhdata$TV.mean==52,1,0)
hhdata$tv_53 <- ifelse(hhdata$TV.mean==53,1,0)
hhdata$tv_54 <- ifelse(hhdata$TV.mean==54,1,0)
hhdata$tv_99 <- ifelse(hhdata$TV.mean==99,1,0)
# Create Collapsed Variable: TV
tv_00 <- summaryBy(tv_00 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_10 <- summaryBy(tv_10 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_20 <- summaryBy(tv_20 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_21 <- summaryBy(tv_21 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_22 <- summaryBy(tv_22 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_23 <- summaryBy(tv_23 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_24 <- summaryBy(tv_24 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_25 <- summaryBy(tv_25 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_26 <- summaryBy(tv_26 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_27 <- summaryBy(tv_27 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_28 <- summaryBy(tv_28 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_29 <- summaryBy(tv_29 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_30 <- summaryBy(tv_30 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_31 <- summaryBy(tv_31 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_32 <- summaryBy(tv_32 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_33 <- summaryBy(tv_33 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_40 <- summaryBy(tv_40 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_41 <- summaryBy(tv_41 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_42 <- summaryBy(tv_42 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_43 <- summaryBy(tv_43 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_50 <- summaryBy(tv_50 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_52 <- summaryBy(tv_52 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_53 <- summaryBy(tv_53 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_54 <- summaryBy(tv_54 ~ GEO2A_MW, FUN=mean, data=hhdata)
tv_99 <- summaryBy(tv_99 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: TV
tv <- merge(tv_00, tv_10, by="GEO2A_MW")
tv <- merge(tv, tv_20, by="GEO2A_MW")
tv <- merge(tv, tv_21, by="GEO2A_MW")
tv <- merge(tv, tv_22, by="GEO2A_MW")
tv <- merge(tv, tv_23, by="GEO2A_MW")
tv <- merge(tv, tv_24, by="GEO2A_MW")
tv <- merge(tv, tv_25, by="GEO2A_MW")
tv <- merge(tv, tv_26, by="GEO2A_MW")
tv <- merge(tv, tv_27, by="GEO2A_MW")
tv <- merge(tv, tv_28, by="GEO2A_MW")
tv <- merge(tv, tv_29, by="GEO2A_MW")
tv <- merge(tv, tv_30, by="GEO2A_MW")
tv <- merge(tv, tv_31, by="GEO2A_MW")
tv <- merge(tv, tv_32, by="GEO2A_MW")
tv <- merge(tv, tv_33, by="GEO2A_MW")
tv <- merge(tv, tv_40, by="GEO2A_MW")
tv <- merge(tv, tv_41, by="GEO2A_MW")
tv <- merge(tv, tv_42, by="GEO2A_MW")
tv <- merge(tv, tv_43, by="GEO2A_MW")
tv <- merge(tv, tv_50, by="GEO2A_MW")
tv <- merge(tv, tv_52, by="GEO2A_MW")
tv <- merge(tv, tv_53, by="GEO2A_MW")
tv <- merge(tv, tv_54, by="GEO2A_MW")
tv <- merge(tv, tv_99, by="GEO2A_MW")


# Separate Variable: RADIO
hhdata$radio_0 <- ifelse(hhdata$RADIO.mean==0,1,0)
hhdata$radio_1 <- ifelse(hhdata$RADIO.mean==1,1,0)
hhdata$radio_2 <- ifelse(hhdata$RADIO.mean==2,1,0)
hhdata$radio_9 <- ifelse(hhdata$RADIO.mean==9,1,0)
# Create Collapsed Variabes: RADIO
radio_0 <- summaryBy(radio_0 ~ GEO2A_MW, FUN=mean, data=hhdata)
radio_1 <- summaryBy(radio_1 ~ GEO2A_MW, FUN=mean, data=hhdata)
radio_2 <- summaryBy(radio_2 ~ GEO2A_MW, FUN=mean, data=hhdata)
radio_9 <- summaryBy(radio_9 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: RADIO
radio <- merge(radio_0, radio_1, by="GEO2A_MW")
radio <- merge(radio, radio_2, by="GEO2A_MW")
radio <- merge(radio, radio_9, by="GEO2A_MW")


# Remove unknown values: ROOMS
hhdata$ROOMS.mean[hhdata$ROOMS.mean==98] <- NA
hhdata$ROOMS.mean[hhdata$ROOMS.mean==99] <- NA
# Create Collapsed Variable: ROOMS
rooms <- summaryBy(ROOMS.mean ~ GEO2A_MW, FUN=narm_mean, data=hhdata)


# Remove unknown values: BEDRMS
hhdata$BEDRMS.mean[hhdata$BEDRMS.mean==98] <- NA
hhdata$BEDRMS.mean[hhdata$BEDRMS.mean==99] <- NA
# Create Collapsed Variable: BEDRMS
bedrms <- summaryBy(BEDRMS.mean ~ GEO2A_MW, FUN=narm_mean, data=hhdata)


# Separate Variable: TOILET
hhdata$toilet_00 <- ifelse(hhdata$TOILET.mean==00,1,0)
hhdata$toilet_10 <- ifelse(hhdata$TOILET.mean==10,1,0)
hhdata$toilet_11 <- ifelse(hhdata$TOILET.mean==11,1,0)
hhdata$toilet_20 <- ifelse(hhdata$TOILET.mean==20,1,0)
hhdata$toilet_21 <- ifelse(hhdata$TOILET.mean==21,1,0)
hhdata$toilet_22 <- ifelse(hhdata$TOILET.mean==22,1,0)
hhdata$toilet_23 <- ifelse(hhdata$TOILET.mean==23,1,0)
hhdata$toilet_99 <- ifelse(hhdata$TOILET.mean==99,1,0)
# Create Collapsed Variabes: TOILET
toilet_00 <- summaryBy(toilet_00 ~ GEO2A_MW, FUN=mean, data=hhdata)
toilet_10 <- summaryBy(toilet_10 ~ GEO2A_MW, FUN=mean, data=hhdata)
toilet_11 <- summaryBy(toilet_11 ~ GEO2A_MW, FUN=mean, data=hhdata)
toilet_20 <- summaryBy(toilet_20 ~ GEO2A_MW, FUN=mean, data=hhdata)
toilet_21 <- summaryBy(toilet_21 ~ GEO2A_MW, FUN=mean, data=hhdata)
toilet_22 <- summaryBy(toilet_22 ~ GEO2A_MW, FUN=mean, data=hhdata)
toilet_23 <- summaryBy(toilet_23 ~ GEO2A_MW, FUN=mean, data=hhdata)
toilet_99 <- summaryBy(toilet_99 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: TOILET
toilet <- merge(toilet_00, toilet_10, by="GEO2A_MW")
toilet <- merge(toilet, toilet_11, by="GEO2A_MW")
toilet <- merge(toilet, toilet_20, by="GEO2A_MW")
toilet <- merge(toilet, toilet_21, by="GEO2A_MW")
toilet <- merge(toilet, toilet_22, by="GEO2A_MW")
toilet <- merge(toilet, toilet_23, by="GEO2A_MW")
toilet <- merge(toilet, toilet_99, by="GEO2A_MW")


# Separate Variable: FLOOR
hhdata$floor_000 <- ifelse(hhdata$FLOOR.mean==000,1,0)
hhdata$floor_100 <- ifelse(hhdata$FLOOR.mean==100,1,0)
hhdata$floor_110 <- ifelse(hhdata$FLOOR.mean==110,1,0)
hhdata$floor_120 <- ifelse(hhdata$FLOOR.mean==120,1,0)
hhdata$floor_200 <- ifelse(hhdata$FLOOR.mean==200,1,0)
hhdata$floor_201 <- ifelse(hhdata$FLOOR.mean==201,1,0)
hhdata$floor_202 <- ifelse(hhdata$FLOOR.mean==202,1,0)
hhdata$floor_203 <- ifelse(hhdata$FLOOR.mean==203,1,0)
hhdata$floor_204 <- ifelse(hhdata$FLOOR.mean==204,1,0)
hhdata$floor_205 <- ifelse(hhdata$FLOOR.mean==205,1,0)
hhdata$floor_206 <- ifelse(hhdata$FLOOR.mean==206,1,0)
hhdata$floor_207 <- ifelse(hhdata$FLOOR.mean==207,1,0)
hhdata$floor_208 <- ifelse(hhdata$FLOOR.mean==208,1,0)
hhdata$floor_209 <- ifelse(hhdata$FLOOR.mean==209,1,0)
hhdata$floor_210 <- ifelse(hhdata$FLOOR.mean==210,1,0)
hhdata$floor_211 <- ifelse(hhdata$FLOOR.mean==211,1,0)
hhdata$floor_212 <- ifelse(hhdata$FLOOR.mean==212,1,0)
hhdata$floor_213 <- ifelse(hhdata$FLOOR.mean==213,1,0)
hhdata$floor_214 <- ifelse(hhdata$FLOOR.mean==214,1,0)
hhdata$floor_215 <- ifelse(hhdata$FLOOR.mean==215,1,0)
hhdata$floor_216 <- ifelse(hhdata$FLOOR.mean==216,1,0)
hhdata$floor_217 <- ifelse(hhdata$FLOOR.mean==217,1,0)
hhdata$floor_218 <- ifelse(hhdata$FLOOR.mean==218,1,0)
hhdata$floor_219 <- ifelse(hhdata$FLOOR.mean==219,1,0)
hhdata$floor_220 <- ifelse(hhdata$FLOOR.mean==220,1,0)
hhdata$floor_221 <- ifelse(hhdata$FLOOR.mean==221,1,0)
hhdata$floor_222 <- ifelse(hhdata$FLOOR.mean==222,1,0)
hhdata$floor_223 <- ifelse(hhdata$FLOOR.mean==223,1,0)
hhdata$floor_224 <- ifelse(hhdata$FLOOR.mean==224,1,0)
hhdata$floor_225 <- ifelse(hhdata$FLOOR.mean==225,1,0)
hhdata$floor_226 <- ifelse(hhdata$FLOOR.mean==226,1,0)
hhdata$floor_227 <- ifelse(hhdata$FLOOR.mean==227,1,0)
hhdata$floor_228 <- ifelse(hhdata$FLOOR.mean==228,1,0)
hhdata$floor_229 <- ifelse(hhdata$FLOOR.mean==229,1,0)
hhdata$floor_230 <- ifelse(hhdata$FLOOR.mean==230,1,0)
hhdata$floor_231 <- ifelse(hhdata$FLOOR.mean==231,1,0)
hhdata$floor_232 <- ifelse(hhdata$FLOOR.mean==232,1,0)
hhdata$floor_233 <- ifelse(hhdata$FLOOR.mean==233,1,0)
hhdata$floor_234 <- ifelse(hhdata$FLOOR.mean==234,1,0)
hhdata$floor_235 <- ifelse(hhdata$FLOOR.mean==235,1,0)
hhdata$floor_236 <- ifelse(hhdata$FLOOR.mean==236,1,0)
hhdata$floor_999 <- ifelse(hhdata$FLOOR.mean==999,1,0)
# Create Collapsed Variabes: FLOOR
floor_000 <- summaryBy(floor_000 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_100 <- summaryBy(floor_100 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_110 <- summaryBy(floor_110 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_120 <- summaryBy(floor_120 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_200 <- summaryBy(floor_200 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_201 <- summaryBy(floor_201 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_202 <- summaryBy(floor_202 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_203 <- summaryBy(floor_203 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_204 <- summaryBy(floor_204 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_205 <- summaryBy(floor_205 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_206 <- summaryBy(floor_206 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_207 <- summaryBy(floor_207 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_208 <- summaryBy(floor_208 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_209 <- summaryBy(floor_209 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_210 <- summaryBy(floor_210 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_211 <- summaryBy(floor_211 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_212 <- summaryBy(floor_212 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_213 <- summaryBy(floor_213 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_214 <- summaryBy(floor_214 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_215 <- summaryBy(floor_215 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_216 <- summaryBy(floor_216 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_217 <- summaryBy(floor_217 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_218 <- summaryBy(floor_218 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_219 <- summaryBy(floor_219 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_220 <- summaryBy(floor_220 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_221 <- summaryBy(floor_221 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_222 <- summaryBy(floor_222 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_223 <- summaryBy(floor_223 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_224 <- summaryBy(floor_224 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_225 <- summaryBy(floor_225 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_226 <- summaryBy(floor_226 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_227 <- summaryBy(floor_227 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_228 <- summaryBy(floor_228 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_229 <- summaryBy(floor_229 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_230 <- summaryBy(floor_230 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_231 <- summaryBy(floor_231 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_232 <- summaryBy(floor_232 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_233 <- summaryBy(floor_233 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_234 <- summaryBy(floor_234 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_235 <- summaryBy(floor_235 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_236 <- summaryBy(floor_236 ~ GEO2A_MW, FUN=mean, data=hhdata)
floor_999 <- summaryBy(floor_999 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: FLOOR
floor <- merge(floor_000, floor_100, by="GEO2A_MW")
floor <- merge(floor, floor_110, by="GEO2A_MW")
floor <- merge(floor, floor_120, by="GEO2A_MW")
floor <- merge(floor, floor_200, by="GEO2A_MW")
floor <- merge(floor, floor_201, by="GEO2A_MW")
floor <- merge(floor, floor_202, by="GEO2A_MW")
floor <- merge(floor, floor_203, by="GEO2A_MW")
floor <- merge(floor, floor_204, by="GEO2A_MW")
floor <- merge(floor, floor_205, by="GEO2A_MW")
floor <- merge(floor, floor_206, by="GEO2A_MW")
floor <- merge(floor, floor_207, by="GEO2A_MW")
floor <- merge(floor, floor_208, by="GEO2A_MW")
floor <- merge(floor, floor_209, by="GEO2A_MW")
floor <- merge(floor, floor_210, by="GEO2A_MW")
floor <- merge(floor, floor_211, by="GEO2A_MW")
floor <- merge(floor, floor_212, by="GEO2A_MW")
floor <- merge(floor, floor_213, by="GEO2A_MW")
floor <- merge(floor, floor_214, by="GEO2A_MW")
floor <- merge(floor, floor_215, by="GEO2A_MW")
floor <- merge(floor, floor_216, by="GEO2A_MW")
floor <- merge(floor, floor_217, by="GEO2A_MW")
floor <- merge(floor, floor_218, by="GEO2A_MW")
floor <- merge(floor, floor_219, by="GEO2A_MW")
floor <- merge(floor, floor_220, by="GEO2A_MW")
floor <- merge(floor, floor_221, by="GEO2A_MW")
floor <- merge(floor, floor_222, by="GEO2A_MW")
floor <- merge(floor, floor_223, by="GEO2A_MW")
floor <- merge(floor, floor_224, by="GEO2A_MW")
floor <- merge(floor, floor_225, by="GEO2A_MW")
floor <- merge(floor, floor_226, by="GEO2A_MW")
floor <- merge(floor, floor_227, by="GEO2A_MW")
floor <- merge(floor, floor_228, by="GEO2A_MW")
floor <- merge(floor, floor_229, by="GEO2A_MW")
floor <- merge(floor, floor_230, by="GEO2A_MW")
floor <- merge(floor, floor_231, by="GEO2A_MW")
floor <- merge(floor, floor_232, by="GEO2A_MW")
floor <- merge(floor, floor_233, by="GEO2A_MW")
floor <- merge(floor, floor_234, by="GEO2A_MW")
floor <- merge(floor, floor_235, by="GEO2A_MW")
floor <- merge(floor, floor_236, by="GEO2A_MW")
floor <- merge(floor, floor_999, by="GEO2A_MW")


# Separate Variable: WALL
hhdata$wall_000 <- ifelse(hhdata$WALL.mean==000,1,0)
hhdata$wall_100 <- ifelse(hhdata$WALL.mean==100,1,0)
hhdata$wall_200 <- ifelse(hhdata$WALL.mean==200,1,0)
hhdata$wall_201 <- ifelse(hhdata$WALL.mean==201,1,0)
hhdata$wall_202 <- ifelse(hhdata$WALL.mean==202,1,0)
hhdata$wall_203 <- ifelse(hhdata$WALL.mean==203,1,0)
hhdata$wall_204 <- ifelse(hhdata$WALL.mean==204,1,0)
hhdata$wall_205 <- ifelse(hhdata$WALL.mean==205,1,0)
hhdata$wall_206 <- ifelse(hhdata$WALL.mean==206,1,0)
hhdata$wall_207 <- ifelse(hhdata$WALL.mean==207,1,0)
hhdata$wall_300 <- ifelse(hhdata$WALL.mean==300,1,0)
hhdata$wall_310 <- ifelse(hhdata$WALL.mean==310,1,0)
hhdata$wall_320 <- ifelse(hhdata$WALL.mean==320,1,0)
hhdata$wall_330 <- ifelse(hhdata$WALL.mean==330,1,0)
hhdata$wall_340 <- ifelse(hhdata$WALL.mean==340,1,0)
hhdata$wall_350 <- ifelse(hhdata$WALL.mean==350,1,0)
hhdata$wall_400 <- ifelse(hhdata$WALL.mean==400,1,0)
hhdata$wall_401 <- ifelse(hhdata$WALL.mean==401,1,0)
hhdata$wall_402 <- ifelse(hhdata$WALL.mean==402,1,0)
hhdata$wall_403 <- ifelse(hhdata$WALL.mean==403,1,0)
hhdata$wall_404 <- ifelse(hhdata$WALL.mean==404,1,0)
hhdata$wall_405 <- ifelse(hhdata$WALL.mean==405,1,0)
hhdata$wall_406 <- ifelse(hhdata$WALL.mean==406,1,0)
hhdata$wall_407 <- ifelse(hhdata$WALL.mean==407,1,0)
hhdata$wall_408 <- ifelse(hhdata$WALL.mean==408,1,0)
hhdata$wall_500 <- ifelse(hhdata$WALL.mean==500,1,0)
hhdata$wall_501 <- ifelse(hhdata$WALL.mean==501,1,0)
hhdata$wall_502 <- ifelse(hhdata$WALL.mean==502,1,0)
hhdata$wall_503 <- ifelse(hhdata$WALL.mean==503,1,0)
hhdata$wall_504 <- ifelse(hhdata$WALL.mean==504,1,0)
hhdata$wall_505 <- ifelse(hhdata$WALL.mean==505,1,0)
hhdata$wall_506 <- ifelse(hhdata$WALL.mean==506,1,0)
hhdata$wall_507 <- ifelse(hhdata$WALL.mean==507,1,0)
hhdata$wall_508 <- ifelse(hhdata$WALL.mean==508,1,0)
hhdata$wall_509 <- ifelse(hhdata$WALL.mean==509,1,0)
hhdata$wall_510 <- ifelse(hhdata$WALL.mean==510,1,0)
hhdata$wall_511 <- ifelse(hhdata$WALL.mean==511,1,0)
hhdata$wall_512 <- ifelse(hhdata$WALL.mean==512,1,0)
hhdata$wall_513 <- ifelse(hhdata$WALL.mean==513,1,0)
hhdata$wall_514 <- ifelse(hhdata$WALL.mean==514,1,0)
hhdata$wall_515 <- ifelse(hhdata$WALL.mean==515,1,0)
hhdata$wall_516 <- ifelse(hhdata$WALL.mean==516,1,0)
hhdata$wall_517 <- ifelse(hhdata$WALL.mean==517,1,0)
hhdata$wall_518 <- ifelse(hhdata$WALL.mean==518,1,0)
hhdata$wall_519 <- ifelse(hhdata$WALL.mean==519,1,0)
hhdata$wall_520 <- ifelse(hhdata$WALL.mean==520,1,0)
hhdata$wall_521 <- ifelse(hhdata$WALL.mean==521,1,0)
hhdata$wall_522 <- ifelse(hhdata$WALL.mean==522,1,0)
hhdata$wall_523 <- ifelse(hhdata$WALL.mean==523,1,0)
hhdata$wall_524 <- ifelse(hhdata$WALL.mean==524,1,0)
hhdata$wall_525 <- ifelse(hhdata$WALL.mean==525,1,0)
hhdata$wall_526 <- ifelse(hhdata$WALL.mean==526,1,0)
hhdata$wall_527 <- ifelse(hhdata$WALL.mean==527,1,0)
hhdata$wall_528 <- ifelse(hhdata$WALL.mean==528,1,0)
hhdata$wall_529 <- ifelse(hhdata$WALL.mean==529,1,0)
hhdata$wall_530 <- ifelse(hhdata$WALL.mean==530,1,0)
hhdata$wall_531 <- ifelse(hhdata$WALL.mean==531,1,0)
hhdata$wall_532 <- ifelse(hhdata$WALL.mean==532,1,0)
hhdata$wall_533 <- ifelse(hhdata$WALL.mean==533,1,0)
hhdata$wall_534 <- ifelse(hhdata$WALL.mean==534,1,0)
hhdata$wall_535 <- ifelse(hhdata$WALL.mean==535,1,0)
hhdata$wall_536 <- ifelse(hhdata$WALL.mean==536,1,0)
hhdata$wall_537 <- ifelse(hhdata$WALL.mean==537,1,0)
hhdata$wall_538 <- ifelse(hhdata$WALL.mean==538,1,0)
hhdata$wall_539 <- ifelse(hhdata$WALL.mean==539,1,0)
hhdata$wall_540 <- ifelse(hhdata$WALL.mean==540,1,0)
hhdata$wall_541 <- ifelse(hhdata$WALL.mean==541,1,0)
hhdata$wall_542 <- ifelse(hhdata$WALL.mean==542,1,0)
hhdata$wall_543 <- ifelse(hhdata$WALL.mean==543,1,0)
hhdata$wall_544 <- ifelse(hhdata$WALL.mean==544,1,0)
hhdata$wall_545 <- ifelse(hhdata$WALL.mean==545,1,0)
hhdata$wall_546 <- ifelse(hhdata$WALL.mean==546,1,0)
hhdata$wall_547 <- ifelse(hhdata$WALL.mean==547,1,0)
hhdata$wall_548 <- ifelse(hhdata$WALL.mean==548,1,0)
hhdata$wall_549 <- ifelse(hhdata$WALL.mean==549,1,0)
hhdata$wall_550 <- ifelse(hhdata$WALL.mean==550,1,0)
hhdata$wall_551 <- ifelse(hhdata$WALL.mean==551,1,0)
hhdata$wall_552 <- ifelse(hhdata$WALL.mean==552,1,0)
hhdata$wall_553 <- ifelse(hhdata$WALL.mean==553,1,0)
hhdata$wall_554 <- ifelse(hhdata$WALL.mean==554,1,0)
hhdata$wall_555 <- ifelse(hhdata$WALL.mean==555,1,0)
hhdata$wall_556 <- ifelse(hhdata$WALL.mean==556,1,0)
hhdata$wall_557 <- ifelse(hhdata$WALL.mean==557,1,0)
hhdata$wall_558 <- ifelse(hhdata$WALL.mean==558,1,0)
hhdata$wall_559 <- ifelse(hhdata$WALL.mean==559,1,0)
hhdata$wall_560 <- ifelse(hhdata$WALL.mean==560,1,0)
hhdata$wall_561 <- ifelse(hhdata$WALL.mean==561,1,0)
hhdata$wall_570 <- ifelse(hhdata$WALL.mean==570,1,0)
hhdata$wall_600 <- ifelse(hhdata$WALL.mean==600,1,0)
hhdata$wall_999 <- ifelse(hhdata$WALL.mean==999,1,0)
# Create Collapsed Variabes: WALL
wall_000 <- summaryBy(wall_000 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_100 <- summaryBy(wall_100 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_200 <- summaryBy(wall_200 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_201 <- summaryBy(wall_201 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_202 <- summaryBy(wall_202 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_203 <- summaryBy(wall_203 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_204 <- summaryBy(wall_204 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_205 <- summaryBy(wall_205 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_206 <- summaryBy(wall_206 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_207 <- summaryBy(wall_207 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_300 <- summaryBy(wall_300 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_310 <- summaryBy(wall_310 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_320 <- summaryBy(wall_320 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_330 <- summaryBy(wall_330 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_340 <- summaryBy(wall_340 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_350 <- summaryBy(wall_350 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_400 <- summaryBy(wall_400 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_401 <- summaryBy(wall_401 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_402 <- summaryBy(wall_402 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_403 <- summaryBy(wall_403 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_404 <- summaryBy(wall_404 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_405 <- summaryBy(wall_405 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_406 <- summaryBy(wall_406 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_407 <- summaryBy(wall_407 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_408 <- summaryBy(wall_408 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_500 <- summaryBy(wall_500 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_501 <- summaryBy(wall_501 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_502 <- summaryBy(wall_502 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_503 <- summaryBy(wall_503 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_504 <- summaryBy(wall_504 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_505 <- summaryBy(wall_505 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_506 <- summaryBy(wall_506 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_507 <- summaryBy(wall_507 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_508 <- summaryBy(wall_508 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_509 <- summaryBy(wall_509 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_510 <- summaryBy(wall_510 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_511 <- summaryBy(wall_511 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_512 <- summaryBy(wall_512 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_513 <- summaryBy(wall_513 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_514 <- summaryBy(wall_514 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_515 <- summaryBy(wall_515 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_516 <- summaryBy(wall_516 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_517 <- summaryBy(wall_517 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_518 <- summaryBy(wall_518 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_519 <- summaryBy(wall_519 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_520 <- summaryBy(wall_520 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_521 <- summaryBy(wall_521 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_522 <- summaryBy(wall_522 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_523 <- summaryBy(wall_523 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_524 <- summaryBy(wall_524 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_525 <- summaryBy(wall_525 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_526 <- summaryBy(wall_526 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_527 <- summaryBy(wall_527 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_528 <- summaryBy(wall_528 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_529 <- summaryBy(wall_529 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_530 <- summaryBy(wall_530 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_531 <- summaryBy(wall_531 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_532 <- summaryBy(wall_532 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_533 <- summaryBy(wall_533 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_534 <- summaryBy(wall_534 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_535 <- summaryBy(wall_535 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_536 <- summaryBy(wall_536 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_537 <- summaryBy(wall_537 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_538 <- summaryBy(wall_538 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_539 <- summaryBy(wall_539 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_540 <- summaryBy(wall_540 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_541 <- summaryBy(wall_541 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_542 <- summaryBy(wall_542 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_543 <- summaryBy(wall_543 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_544 <- summaryBy(wall_544 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_545 <- summaryBy(wall_545 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_546 <- summaryBy(wall_546 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_547 <- summaryBy(wall_547 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_548 <- summaryBy(wall_548 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_549 <- summaryBy(wall_549 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_550 <- summaryBy(wall_550 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_551 <- summaryBy(wall_551 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_552 <- summaryBy(wall_552 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_553 <- summaryBy(wall_553 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_554 <- summaryBy(wall_554 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_555 <- summaryBy(wall_555 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_556 <- summaryBy(wall_556 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_557 <- summaryBy(wall_557 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_558 <- summaryBy(wall_558 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_559 <- summaryBy(wall_559 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_560 <- summaryBy(wall_560 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_561 <- summaryBy(wall_561 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_570 <- summaryBy(wall_570 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_600 <- summaryBy(wall_600 ~ GEO2A_MW, FUN=mean, data=hhdata)
wall_999 <- summaryBy(wall_999 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: WALL
wall <- merge(wall_000, wall_100, by="GEO2A_MW")
wall <- merge(wall, wall_200, by="GEO2A_MW")
wall <- merge(wall, wall_201, by="GEO2A_MW")
wall <- merge(wall, wall_202, by="GEO2A_MW")
wall <- merge(wall, wall_203, by="GEO2A_MW")
wall <- merge(wall, wall_204, by="GEO2A_MW")
wall <- merge(wall, wall_205, by="GEO2A_MW")
wall <- merge(wall, wall_206, by="GEO2A_MW")
wall <- merge(wall, wall_207, by="GEO2A_MW")
wall <- merge(wall, wall_300, by="GEO2A_MW")
wall <- merge(wall, wall_310, by="GEO2A_MW")
wall <- merge(wall, wall_320, by="GEO2A_MW")
wall <- merge(wall, wall_330, by="GEO2A_MW")
wall <- merge(wall, wall_340, by="GEO2A_MW")
wall <- merge(wall, wall_350, by="GEO2A_MW")
wall <- merge(wall, wall_400, by="GEO2A_MW")
wall <- merge(wall, wall_401, by="GEO2A_MW")
wall <- merge(wall, wall_402, by="GEO2A_MW")
wall <- merge(wall, wall_403, by="GEO2A_MW")
wall <- merge(wall, wall_404, by="GEO2A_MW")
wall <- merge(wall, wall_405, by="GEO2A_MW")
wall <- merge(wall, wall_406, by="GEO2A_MW")
wall <- merge(wall, wall_407, by="GEO2A_MW")
wall <- merge(wall, wall_408, by="GEO2A_MW")
wall <- merge(wall, wall_500, by="GEO2A_MW")
wall <- merge(wall, wall_501, by="GEO2A_MW")
wall <- merge(wall, wall_502, by="GEO2A_MW")
wall <- merge(wall, wall_503, by="GEO2A_MW")
wall <- merge(wall, wall_504, by="GEO2A_MW")
wall <- merge(wall, wall_505, by="GEO2A_MW")
wall <- merge(wall, wall_506, by="GEO2A_MW")
wall <- merge(wall, wall_507, by="GEO2A_MW")
wall <- merge(wall, wall_508, by="GEO2A_MW")
wall <- merge(wall, wall_509, by="GEO2A_MW")
wall <- merge(wall, wall_510, by="GEO2A_MW")
wall <- merge(wall, wall_511, by="GEO2A_MW")
wall <- merge(wall, wall_512, by="GEO2A_MW")
wall <- merge(wall, wall_513, by="GEO2A_MW")
wall <- merge(wall, wall_514, by="GEO2A_MW")
wall <- merge(wall, wall_515, by="GEO2A_MW")
wall <- merge(wall, wall_516, by="GEO2A_MW")
wall <- merge(wall, wall_517, by="GEO2A_MW")
wall <- merge(wall, wall_518, by="GEO2A_MW")
wall <- merge(wall, wall_519, by="GEO2A_MW")
wall <- merge(wall, wall_520, by="GEO2A_MW")
wall <- merge(wall, wall_521, by="GEO2A_MW")
wall <- merge(wall, wall_522, by="GEO2A_MW")
wall <- merge(wall, wall_523, by="GEO2A_MW")
wall <- merge(wall, wall_524, by="GEO2A_MW")
wall <- merge(wall, wall_525, by="GEO2A_MW")
wall <- merge(wall, wall_526, by="GEO2A_MW")
wall <- merge(wall, wall_527, by="GEO2A_MW")
wall <- merge(wall, wall_528, by="GEO2A_MW")
wall <- merge(wall, wall_529, by="GEO2A_MW")
wall <- merge(wall, wall_530, by="GEO2A_MW")
wall <- merge(wall, wall_531, by="GEO2A_MW")
wall <- merge(wall, wall_532, by="GEO2A_MW")
wall <- merge(wall, wall_533, by="GEO2A_MW")
wall <- merge(wall, wall_534, by="GEO2A_MW")
wall <- merge(wall, wall_535, by="GEO2A_MW")
wall <- merge(wall, wall_536, by="GEO2A_MW")
wall <- merge(wall, wall_537, by="GEO2A_MW")
wall <- merge(wall, wall_538, by="GEO2A_MW")
wall <- merge(wall, wall_539, by="GEO2A_MW")
wall <- merge(wall, wall_540, by="GEO2A_MW")
wall <- merge(wall, wall_541, by="GEO2A_MW")
wall <- merge(wall, wall_542, by="GEO2A_MW")
wall <- merge(wall, wall_543, by="GEO2A_MW")
wall <- merge(wall, wall_544, by="GEO2A_MW")
wall <- merge(wall, wall_545, by="GEO2A_MW")
wall <- merge(wall, wall_546, by="GEO2A_MW")
wall <- merge(wall, wall_547, by="GEO2A_MW")
wall <- merge(wall, wall_548, by="GEO2A_MW")
wall <- merge(wall, wall_549, by="GEO2A_MW")
wall <- merge(wall, wall_550, by="GEO2A_MW")
wall <- merge(wall, wall_551, by="GEO2A_MW")
wall <- merge(wall, wall_552, by="GEO2A_MW")
wall <- merge(wall, wall_553, by="GEO2A_MW")
wall <- merge(wall, wall_554, by="GEO2A_MW")
wall <- merge(wall, wall_555, by="GEO2A_MW")
wall <- merge(wall, wall_556, by="GEO2A_MW")
wall <- merge(wall, wall_557, by="GEO2A_MW")
wall <- merge(wall, wall_558, by="GEO2A_MW")
wall <- merge(wall, wall_559, by="GEO2A_MW")
wall <- merge(wall, wall_560, by="GEO2A_MW")
wall <- merge(wall, wall_561, by="GEO2A_MW")
wall <- merge(wall, wall_570, by="GEO2A_MW")
wall <- merge(wall, wall_600, by="GEO2A_MW")
wall <- merge(wall, wall_999, by="GEO2A_MW")


# Separate Variable: ROOF
hhdata$roof_00 <- ifelse(hhdata$ROOF.mean==00,1,0)
hhdata$roof_10 <- ifelse(hhdata$ROOF.mean==10,1,0)
hhdata$roof_11 <- ifelse(hhdata$ROOF.mean==11,1,0)
hhdata$roof_12 <- ifelse(hhdata$ROOF.mean==12,1,0)
hhdata$roof_13 <- ifelse(hhdata$ROOF.mean==13,1,0)
hhdata$roof_14 <- ifelse(hhdata$ROOF.mean==14,1,0)
hhdata$roof_15 <- ifelse(hhdata$ROOF.mean==15,1,0)
hhdata$roof_16 <- ifelse(hhdata$ROOF.mean==16,1,0)
hhdata$roof_17 <- ifelse(hhdata$ROOF.mean==17,1,0)
hhdata$roof_18 <- ifelse(hhdata$ROOF.mean==18,1,0)
hhdata$roof_19 <- ifelse(hhdata$ROOF.mean==19,1,0)
hhdata$roof_20 <- ifelse(hhdata$ROOF.mean==20,1,0)
hhdata$roof_21 <- ifelse(hhdata$ROOF.mean==21,1,0)
hhdata$roof_22 <- ifelse(hhdata$ROOF.mean==22,1,0)
hhdata$roof_23 <- ifelse(hhdata$ROOF.mean==23,1,0)
hhdata$roof_24 <- ifelse(hhdata$ROOF.mean==24,1,0)
hhdata$roof_25 <- ifelse(hhdata$ROOF.mean==25,1,0)
hhdata$roof_26 <- ifelse(hhdata$ROOF.mean==26,1,0)
hhdata$roof_27 <- ifelse(hhdata$ROOF.mean==27,1,0)
hhdata$roof_28 <- ifelse(hhdata$ROOF.mean==28,1,0)
hhdata$roof_29 <- ifelse(hhdata$ROOF.mean==29,1,0)
hhdata$roof_30 <- ifelse(hhdata$ROOF.mean==30,1,0)
hhdata$roof_31 <- ifelse(hhdata$ROOF.mean==31,1,0)
hhdata$roof_32 <- ifelse(hhdata$ROOF.mean==32,1,0)
hhdata$roof_33 <- ifelse(hhdata$ROOF.mean==33,1,0)
hhdata$roof_34 <- ifelse(hhdata$ROOF.mean==34,1,0)
hhdata$roof_35 <- ifelse(hhdata$ROOF.mean==35,1,0)
hhdata$roof_40 <- ifelse(hhdata$ROOF.mean==40,1,0)
hhdata$roof_41 <- ifelse(hhdata$ROOF.mean==41,1,0)
hhdata$roof_42 <- ifelse(hhdata$ROOF.mean==42,1,0)
hhdata$roof_43 <- ifelse(hhdata$ROOF.mean==43,1,0)
hhdata$roof_44 <- ifelse(hhdata$ROOF.mean==44,1,0)
hhdata$roof_45 <- ifelse(hhdata$ROOF.mean==45,1,0)
hhdata$roof_46 <- ifelse(hhdata$ROOF.mean==46,1,0)
hhdata$roof_47 <- ifelse(hhdata$ROOF.mean==47,1,0)
hhdata$roof_48 <- ifelse(hhdata$ROOF.mean==48,1,0)
hhdata$roof_49 <- ifelse(hhdata$ROOF.mean==49,1,0)
hhdata$roof_50 <- ifelse(hhdata$ROOF.mean==50,1,0)
hhdata$roof_51 <- ifelse(hhdata$ROOF.mean==51,1,0)
hhdata$roof_52 <- ifelse(hhdata$ROOF.mean==52,1,0)
hhdata$roof_53 <- ifelse(hhdata$ROOF.mean==53,1,0)
hhdata$roof_54 <- ifelse(hhdata$ROOF.mean==54,1,0)
hhdata$roof_60 <- ifelse(hhdata$ROOF.mean==60,1,0)
hhdata$roof_61 <- ifelse(hhdata$ROOF.mean==61,1,0)
hhdata$roof_70 <- ifelse(hhdata$ROOF.mean==70,1,0)
hhdata$roof_71 <- ifelse(hhdata$ROOF.mean==71,1,0)
hhdata$roof_72 <- ifelse(hhdata$ROOF.mean==72,1,0)
hhdata$roof_73 <- ifelse(hhdata$ROOF.mean==73,1,0)
hhdata$roof_80 <- ifelse(hhdata$ROOF.mean==80,1,0)
hhdata$roof_99 <- ifelse(hhdata$ROOF.mean==99,1,0)
# Create Collapsed Variabes: ROOF
roof_00 <- summaryBy(roof_00 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_10 <- summaryBy(roof_10 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_11 <- summaryBy(roof_11 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_12 <- summaryBy(roof_12 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_13 <- summaryBy(roof_13 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_14 <- summaryBy(roof_14 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_15 <- summaryBy(roof_15 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_16 <- summaryBy(roof_16 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_17 <- summaryBy(roof_17 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_18 <- summaryBy(roof_18 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_19 <- summaryBy(roof_19 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_20 <- summaryBy(roof_20 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_21 <- summaryBy(roof_21 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_22 <- summaryBy(roof_22 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_23 <- summaryBy(roof_23 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_24 <- summaryBy(roof_24 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_25 <- summaryBy(roof_25 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_26 <- summaryBy(roof_26 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_27 <- summaryBy(roof_27 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_28 <- summaryBy(roof_28 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_29 <- summaryBy(roof_29 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_30 <- summaryBy(roof_30 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_31 <- summaryBy(roof_31 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_32 <- summaryBy(roof_32 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_33 <- summaryBy(roof_33 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_34 <- summaryBy(roof_34 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_35 <- summaryBy(roof_35 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_40 <- summaryBy(roof_40 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_41 <- summaryBy(roof_41 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_42 <- summaryBy(roof_42 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_43 <- summaryBy(roof_43 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_44 <- summaryBy(roof_44 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_45 <- summaryBy(roof_45 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_46 <- summaryBy(roof_46 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_47 <- summaryBy(roof_47 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_48 <- summaryBy(roof_48 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_49 <- summaryBy(roof_49 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_50 <- summaryBy(roof_50 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_51 <- summaryBy(roof_51 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_52 <- summaryBy(roof_52 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_53 <- summaryBy(roof_53 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_54 <- summaryBy(roof_54 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_60 <- summaryBy(roof_60 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_61 <- summaryBy(roof_61 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_70 <- summaryBy(roof_70 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_71 <- summaryBy(roof_71 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_72 <- summaryBy(roof_72 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_73 <- summaryBy(roof_73 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_80 <- summaryBy(roof_80 ~ GEO2A_MW, FUN=mean, data=hhdata)
roof_99 <- summaryBy(roof_99 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: ROOF
roof <- merge(roof_00, roof_10, by="GEO2A_MW")
roof <- merge(roof, roof_11, by="GEO2A_MW")
roof <- merge(roof, roof_12, by="GEO2A_MW")
roof <- merge(roof, roof_13, by="GEO2A_MW")
roof <- merge(roof, roof_14, by="GEO2A_MW")
roof <- merge(roof, roof_15, by="GEO2A_MW")
roof <- merge(roof, roof_16, by="GEO2A_MW")
roof <- merge(roof, roof_17, by="GEO2A_MW")
roof <- merge(roof, roof_18, by="GEO2A_MW")
roof <- merge(roof, roof_19, by="GEO2A_MW")
roof <- merge(roof, roof_20, by="GEO2A_MW")
roof <- merge(roof, roof_21, by="GEO2A_MW")
roof <- merge(roof, roof_22, by="GEO2A_MW")
roof <- merge(roof, roof_23, by="GEO2A_MW")
roof <- merge(roof, roof_24, by="GEO2A_MW")
roof <- merge(roof, roof_25, by="GEO2A_MW")
roof <- merge(roof, roof_26, by="GEO2A_MW")
roof <- merge(roof, roof_27, by="GEO2A_MW")
roof <- merge(roof, roof_28, by="GEO2A_MW")
roof <- merge(roof, roof_29, by="GEO2A_MW")
roof <- merge(roof, roof_30, by="GEO2A_MW")
roof <- merge(roof, roof_31, by="GEO2A_MW")
roof <- merge(roof, roof_32, by="GEO2A_MW")
roof <- merge(roof, roof_33, by="GEO2A_MW")
roof <- merge(roof, roof_34, by="GEO2A_MW")
roof <- merge(roof, roof_35, by="GEO2A_MW")
roof <- merge(roof, roof_40, by="GEO2A_MW")
roof <- merge(roof, roof_41, by="GEO2A_MW")
roof <- merge(roof, roof_42, by="GEO2A_MW")
roof <- merge(roof, roof_43, by="GEO2A_MW")
roof <- merge(roof, roof_44, by="GEO2A_MW")
roof <- merge(roof, roof_45, by="GEO2A_MW")
roof <- merge(roof, roof_46, by="GEO2A_MW")
roof <- merge(roof, roof_47, by="GEO2A_MW")
roof <- merge(roof, roof_48, by="GEO2A_MW")
roof <- merge(roof, roof_49, by="GEO2A_MW")
roof <- merge(roof, roof_50, by="GEO2A_MW")
roof <- merge(roof, roof_51, by="GEO2A_MW")
roof <- merge(roof, roof_52, by="GEO2A_MW")
roof <- merge(roof, roof_53, by="GEO2A_MW")
roof <- merge(roof, roof_54, by="GEO2A_MW")
roof <- merge(roof, roof_60, by="GEO2A_MW")
roof <- merge(roof, roof_61, by="GEO2A_MW")
roof <- merge(roof, roof_70, by="GEO2A_MW")
roof <- merge(roof, roof_71, by="GEO2A_MW")
roof <- merge(roof, roof_72, by="GEO2A_MW")
roof <- merge(roof, roof_73, by="GEO2A_MW")
roof <- merge(roof, roof_80, by="GEO2A_MW")
roof <- merge(roof, roof_99, by="GEO2A_MW")


# Remove unknown values: MORTNUM
hhdata$MORTNUM.mean[hhdata$MORTNUM.mean==8] <- NA
hhdata$MORTNUM.mean[hhdata$MORTNUM.mean==9] <- NA
# Create Collapsed Variable: MORTNUM.mean
mortnum <- summaryBy(MORTNUM.mean ~ GEO2A_MW, FUN=weightsum, data=hhdata)


# Separate Variable: ANYMORT
hhdata$anymort_1 <- ifelse(hhdata$ANYMORT.mean==1,1,0)
hhdata$anymort_2 <- ifelse(hhdata$ANYMORT.mean==2,1,0)
hhdata$anymort_8 <- ifelse(hhdata$ANYMORT.mean==8,1,0)
hhdata$anymort_9 <- ifelse(hhdata$ANYMORT.mean==9,1,0)
# Create Collapsed Variabes: ANYMORT
anymort_1 <- summaryBy(anymort_1 ~ GEO2A_MW, FUN=mean, data=hhdata)
anymort_2 <- summaryBy(anymort_2 ~ GEO2A_MW, FUN=mean, data=hhdata)
anymort_8 <- summaryBy(anymort_8 ~ GEO2A_MW, FUN=mean, data=hhdata)
anymort_9 <- summaryBy(anymort_9 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: ANYMORT
anymort <- merge(anymort_1, anymort_2, by="GEO2A_MW")
anymort <- merge(anymort, anymort_8, by="GEO2A_MW")
anymort <- merge(anymort, anymort_9, by="GEO2A_MW")


# Separate Variable: HHTYPE
hhdata$hhtype_00 <- ifelse(hhdata$HHTYPE.mean==00,1,0)
hhdata$hhtype_01 <- ifelse(hhdata$HHTYPE.mean==01,1,0)
hhdata$hhtype_02 <- ifelse(hhdata$HHTYPE.mean==02,1,0)
hhdata$hhtype_03 <- ifelse(hhdata$HHTYPE.mean==03,1,0)
hhdata$hhtype_04 <- ifelse(hhdata$HHTYPE.mean==04,1,0)
hhdata$hhtype_05 <- ifelse(hhdata$HHTYPE.mean==05,1,0)
hhdata$hhtype_06 <- ifelse(hhdata$HHTYPE.mean==06,1,0)
hhdata$hhtype_07 <- ifelse(hhdata$HHTYPE.mean==07,1,0)
hhdata$hhtype_08 <- ifelse(hhdata$HHTYPE.mean==08,1,0)
hhdata$hhtype_09 <- ifelse(hhdata$HHTYPE.mean==09,1,0)
hhdata$hhtype_10 <- ifelse(hhdata$HHTYPE.mean==10,1,0)
hhdata$hhtype_11 <- ifelse(hhdata$HHTYPE.mean==11,1,0)
hhdata$hhtype_99 <- ifelse(hhdata$HHTYPE.mean==99,1,0)
# Create Collapsed Variabes: HHTYPE
hhtype_00 <- summaryBy(hhtype_00 ~ GEO2A_MW, FUN=mean, data=hhdata)
hhtype_01 <- summaryBy(hhtype_01 ~ GEO2A_MW, FUN=mean, data=hhdata)
hhtype_02 <- summaryBy(hhtype_02 ~ GEO2A_MW, FUN=mean, data=hhdata)
hhtype_03 <- summaryBy(hhtype_03 ~ GEO2A_MW, FUN=mean, data=hhdata)
hhtype_04 <- summaryBy(hhtype_04 ~ GEO2A_MW, FUN=mean, data=hhdata)
hhtype_05 <- summaryBy(hhtype_05 ~ GEO2A_MW, FUN=mean, data=hhdata)
hhtype_06 <- summaryBy(hhtype_06 ~ GEO2A_MW, FUN=mean, data=hhdata)
hhtype_07 <- summaryBy(hhtype_07 ~ GEO2A_MW, FUN=mean, data=hhdata)
hhtype_08 <- summaryBy(hhtype_08 ~ GEO2A_MW, FUN=mean, data=hhdata)
hhtype_09 <- summaryBy(hhtype_09 ~ GEO2A_MW, FUN=mean, data=hhdata)
hhtype_10 <- summaryBy(hhtype_10 ~ GEO2A_MW, FUN=mean, data=hhdata)
hhtype_11 <- summaryBy(hhtype_11 ~ GEO2A_MW, FUN=mean, data=hhdata)
hhtype_99 <- summaryBy(hhtype_99 ~ GEO2A_MW, FUN=mean, data=hhdata)
# Merge: HHTYPE
hhtype <- merge(hhtype_00, hhtype_01, by="GEO2A_MW")
hhtype <- merge(hhtype, hhtype_02, by="GEO2A_MW")
hhtype <- merge(hhtype, hhtype_03, by="GEO2A_MW")
hhtype <- merge(hhtype, hhtype_04, by="GEO2A_MW")
hhtype <- merge(hhtype, hhtype_05, by="GEO2A_MW")
hhtype <- merge(hhtype, hhtype_06, by="GEO2A_MW")
hhtype <- merge(hhtype, hhtype_07, by="GEO2A_MW")
hhtype <- merge(hhtype, hhtype_08, by="GEO2A_MW")
hhtype <- merge(hhtype, hhtype_09, by="GEO2A_MW")
hhtype <- merge(hhtype, hhtype_10, by="GEO2A_MW")
hhtype <- merge(hhtype, hhtype_11, by="GEO2A_MW")
hhtype <- merge(hhtype, hhtype_99, by="GEO2A_MW")


# Create Collapsed Variable: NFAMS
nfams <- summaryBy(NFAMS.mean ~ GEO2A_MW, FUN=weightsum, data=hhdata)


# Create Collapsed Variable: NCOUPLS
ncoupls <- summaryBy(NCOUPLS.mean ~ GEO2A_MW, FUN=weightsum, data=hhdata)


# Create Collapsed Variable: NMOTHRS
nmothrs <- summaryBy(NMOTHRS.mean ~ GEO2A_MW, FUN=weightsum, data=hhdata)


# Create Collapsed Variable: NFATHRS
nfathrs <- summaryBy(NFATHRS.mean ~ GEO2A_MW, FUN=weightsum, data=hhdata)


# Merge All Household Level Variables
mw_2008_hh <- merge(persons, urban, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, unrel, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, ownrshp, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, ownrshpd, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, intmig1, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, remitt, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, electrc, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, watsup, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, fuelck, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, phone, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, autos, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, refrig, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, tv, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, radio, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, rooms, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, bedrms, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, toilet, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, floor, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, wall, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, roof, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, mortnum, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, anymort, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, hhtype, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, nfams, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, ncoupls, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, nmothrs, by="GEO2A_MW")
mw_2008_hh <- merge(mw_2008_hh, nfathrs, by="GEO2A_MW")
